<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>tlobject</artifactId>
        <groupId>cn.tianlong.tlobject</groupId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>tlobject-all</artifactId>
    <dependencies>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>core</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>log-slf4j</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>database</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>cache-filecache</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>cache-ehcache</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>network-client</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>network-proxy</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>network-server-jetty</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>network-server-websocket</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>redis</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>servletutils</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>execl</artifactId>
            <version>1.0</version>
        </dependency>
    </dependencies>

</project>