<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>tlobject</artifactId>
        <groupId>cn.tianlong.tlobject</groupId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>tlobject-all</artifactId>
    <dependencies>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-core</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-log-slf4j</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-crontab</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-database</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-cache-filecache</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-cache-ehcache</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-cache-caffeine</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-network-client</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-network-proxy</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-network-server-jetty</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-network-server-tomcat</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-network-server-websocket</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-network-server-distributedserver</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-redis</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-servletutils</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-execl</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-connectpoolofdb-c3p0</artifactId>
            <version>1.0</version>
        </dependency>
        <dependency>
            <groupId>cn.tianlong.tlobject</groupId>
            <artifactId>tlobject-connectpoolofdb-hikaricp</artifactId>
            <version>1.0</version>
        </dependency>

    </dependencies>

</project>