<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>tlobject</artifactId>
        <groupId>cn.tianlong.tlobject</groupId>
        <version>1.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>tlobject-aiagent</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>common</module>
        <module>provider-openai</module>
        <module>provider-claude</module>
        <module>skill-builtin</module>
        <module>memory-store</module>
    </modules>
</project>
